exe{tests}: {hxx cxx}{**} $chaiscript testscript

# In C++20, using 'std::pod' is deprecated.
#
cxx.coptions += -Wno-deprecated

# Reduce noise from Clang.
#
if ($cxx.id == 'clang')
  cxx.coptions += -Wno-defaulted-function-deleted
