# Building a module for dynamic loading requires a shared library.
# We also make sure to put modules in the same folder.
# These are only private modules and shall not be installed.
#
import lib = libchaiscript%lib{chaiscript}
./: libs{stl_extra}: cxx{stl_extra} $lib
./: libs{test_module}: cxx{test_module} $lib
modules = libs{stl_extra} libs{test_module}
module_path = $out_base

# The ChaiScript interpreter will run the test scripts.
#
import chaiscript = chaiscript%exe{chai}

# All test and inclusion scripts reside in the 'scripts' directory.
# There is also the inclusion script for the unit testing library.
# This was done because there are many scripts and
# it would have been unhandy to put them all into the main test directory.
#
use_path = $src_base/scripts
unit_test_lib = scripts/inc{unit_test}

# Make to also depend on all inclusion files for the 'dist' command.
#
./: scripts/inc{*}

# Probably '3.x' scripts are for backwards compatibility tests.
# Therefore we loop over all subdirectories and let the scripts run.
#
for d: dir{*}
{
  # This transformation is needed to remove the directory type.
  #
  dd = $directory($d)

  # Loop over all given scripts of the specific directory.
  #
  for script: $dd/chai{*}
  {
    # Provide custom 'test' targets for each script that
    # runs the ChaiScript executable with the unit testing library
    # and the script for testing.
    # It is important to provide the correct environment variables
    # for relative inclusion paths and finding modules.
    # The custom empty 'clean' target gets rid of errors
    # when trying to use the clean command.
    #
    ./: $(script)@$dd/: $unit_test_lib $chaiscript $modules
    % clean
    {{
    }}
    % test
    {{
      diag test $>
      env \
        CHAI_USE_PATH="$use_path/" \
        CHAI_MODULE_PATH="$module_path/" \
        -- $chaiscript $path($<[0]) $path($>)
    }}
  }
}

