import chaiscript = libchaiscript%lib{chaiscript}

# Building a module for dynamic loading requires a shared library.
# We also make sure to put modules in the same folder.
# These are only local modules and shall not be installed.
#
./: libs{stl_extra}: cxx{stl_extra} $chaiscript
{
  install = false
}
./: libs{test_module}: cxx{test_module} $chaiscript
{
  install = false
}
