import chaiscript = libchaiscript%lib{chaiscript}

# Building a module for dynamic loading requires a shared library.
#
libs{chaiscript_stdlib}: cxx{**} $chaiscript
{
  cxx.export.libs = $chaiscript
  bin.lib.version = "-$version.major.$version.minor.$version.patch"
}
