import chaiscript = lib{chaiscript}

# Build the shared library that will be used as
# the ChaiScript standard library module
# that can be dynamically loaded at runtime.
#
# It needs to be explicitly specified as target of the directory.
# Otherwise, it is not a default export target
# in the currently provided export inclusion in 'export.build'.
#
./: libs{chaiscript_stdlib}: cxx{**} $chaiscript
{
  # Then naming scheme is important, as it is more or less
  # hardcoded in 'chaiscript/language/chaiscript_engine.hpp'
  #
  bin.lib.version = "-$version.major.$version.minor.$version.patch"

  # To let it be automatically found, its install directory
  # should also follow the patterns given by
  # the 'CMakeLists.txt' file and the header file.
  # This will lead to problems when one would want to adjust the path.
  # The alternative would be to totally leave this
  # up to the install configuration and clearly communicate,
  # that it should be set to one specific location.
  #
  # install = lib/chaiscript/
}
