# Documentation, License, and Package Manifest
#
./: manifest legal{LICENSE} doc{*.md}
doc{UPSTREAM.README.md}@./: install = doc/README.md
doc{README.md}@./: install = doc/PACKAGE.README.md

# ChaiScript Standard Library Module and ChaiScript Interpreter
#
./: static_libs/ chai/
