# Documentation, License, and Package Manifest
#
./: manifest legal{LICENSE} doc{*.md}
doc{UPSTREAM.README.md}@./: install = doc/README.md
doc{README.md}@./: install = doc/PACKAGE.README.md

# ChaiScript Header-Only Library
#
./: lib{chaiscript}: chaiscript/hxx{**}
{
  cxx.export.poptions = "-I$src_root"
}
hxx{*}: install.subdirs = true

# ChaiScript Standard Library Module and ChaiScript Interpreter
#
./: static_libs/ chaiscript_stdlib/ chai/
