# Documentation, License, and Package Manifest
#
./: manifest legal{LICENSE} doc{*.md}
doc{UPSTREAM.README.md}@./: install = doc/README.md
doc{README.md}@./: install = doc/PACKAGE.README.md

# Build the executable and modules.
# The order seems to be important here.
#
./: static_libs/ chai/ modules/ tests/

# Tests will not be installed.
#
tests/: install = false
