# Default Targets and Package Files
#
./: lib{chaiscript} manifest legal{LICENSE} doc{*.md}
./: tests/: install = false

# ChaiScript Header-Only Library
#
lib{chaiscript}: chaiscript/hxx{**}
{
  cxx.export.poptions += $default.export.poptions "-I$src_root"
  cxx.export.coptions += $default.export.coptions
  cxx.export.loptions += $default.export.loptions
  cxx.export.libs += $default.export.libs
}

hxx{*}: install.subdirs = true
