import chaiscript = libchaiscript%lib{chaiscript}

./: libue{parser}: {hxx cxx}{chaiscript_parser} $chaiscript
{
  cxx.export.libs = $chaiscript
}

./: libue{stdlib}: {hxx cxx}{chaiscript_stdlib} $chaiscript
{
  cxx.export.libs = $chaiscript
}
