# The single-header Catch2 library provided
# by the ChaiScript repository may result in compiler errors.
# Hence, we use the build2 package for Catch2 from cppget.org.
#
# The library is included by '#include "catch.hpp"'.
# The file is provided as forwarding mechanism
# to the file 'catch2/catch.hpp'
#
import catch2 = catch2%lib{catch2}

include ../static_libs/
exe{compiled_tests}: {hxx cxx}{**} $catch2 \
  ../static_libs/libue{parser} \
  ../static_libs/libue{stdlib}

if ($cxx.id == 'msvc')
  cxx.coptions += /bigobj
